application: street-view-density
version: dev 
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /javascript
  static_dir: javascript

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /icons
  static_dir: img/icons

- url: /img
  static_dir: img/

- url: /templates
  static_dir: html/templates/

- url: /home(/.*)?$
  static_files: html/index.html
  upload: html/index.html

- url: /.*
  script: entry_point.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: 2.6
